name: my_auto_ml
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates
  - category_encoders=2.2.2
  - certifi
  - cloudpickle
  - decorator
  - et_xmlfile
  - future
  - git
  - hyperopt=0.2.4
  - icc_rt
  - icu
  - imbalanced-learn>=0.7.0
  - intel-openmp
  - jdcal
  - joblib
  - jpeg
  - libblas
  - libcblas
  - libclang
  - liblapack
  - libpng
  - mkl
  - networkx
  - nose
  - numpy>=1.18.5
  - openpyxl
  - openssl
  - pandas>=1.0.5
  - patsy
  - pip
  - pymongo>=3.10.1
  - pyqt>=5.12.3
  - python>=3.8.3
  - python-dateutil
  - python_abi
  - pytz
  - py-xgboost<=1.5.0
  - qt>=5.12.5
  - scikit-learn
  - scipy
  - setuptools
  - six
  - sklearn-contrib-lightning=0.5.0
  - sqlite
  - statsmodels=0.11.1
  - threadpoolctl
  - tqdm
  - vc
  - vs2015_runtime
  - wheel
  - wincertstore
  - zlib
  - pip:
    - gower==0.1.2
    - igraph==0.10.2
    - pymfe==0.4.2
    - texttable==1.6.7
